public enum BuffEventType
{
    //局外事件
    EnterRoom,//进入房间事件
    DestoryObject,//破坏物体
    ItemSelect,//道具获得事件
    ItemGain,//道具获得事件
    ItemGainEffect,//道具获得生效事件
    GoldGain,
    GoldGainEffect,
    //流程事件
    BattleStart,
    BattleEnd,
    TurnStart,
    TurnEnd,
    StageStart,
    StageEnd,
    //获得角色数值
    GetCurrentCharaData,
    //发送技能数据
    SendSkillData,
    //接收技能数据
    ReceiveSkillData,
    ElementalReaction,
    //伤害角色
    Hit,
    //增益角色
    Buff,
    //增益角色
    DeBuff,
    //护盾角色
    Shield,
    //治疗
    Healing,
}
