public enum PlayerType
{
    Traveler,           // 旅行者
    Amber,              // 安柏
    Kaeya,              // 凯亚
    Lisa,               // 丽莎
    Jean,               // 琴
    Barbara,            // 芭芭拉
    Diluc,              // 迪卢克
    Razor,              // 雷泽
    Venti,              // 温蒂
    Klee,               // 可莉
    Tartaglia,          // 达达利亚
    Zhongli,            // 钟离
    Xingqiu,            // 行秋
    Chongyun,           // 重云
    Xiangling,          // 香菱
    Beidou,             // 北斗
    Ningguang,          // 凝光
    Xinyan,             // 辛焱
    Diona,              // 戴奥娜
    Ganyu,              // 甘雨
    Xiao,               // 魈
    Keqing,             // 刻晴
    Qiqi,               // 七七
    Mona,               // 莫娜
    HuTao,              // 胡桃
    Rosaria,            // 罗莎莉亚
    Yanfei,             // 烟绯
    Eula,               // 优菈
    Kazuha,             // 万叶
    KamisatoAyaka,      // 神里绫华
    Yoimiya,            // 宵宫
    Sayu,               // 早柚
    RaidenShogun,       // 雷电将军
    Kokomi,             // 心海
    Aloy,               // 艾洛伊
    Nahida              // 纳西妲
}
